### ISSUE TITLE
Shorter syntax for `validatePresence`

### ISSUE THREAD

**Issue by acamino** [TwilioDevEd/marketing-notifications-servlets#2]
[Here](https://github.com/TwilioDevEd/marketing-notifications-servlets/blob/master/src/main/java/org/twilio/smsmarketing/NotificationsServlet.java#L60) you have this:

```java
return validator.validatePresence("message") && validator.validatePresence("imageUrl");
```

Would you mind replacing that code by:
```java
return validator.validatePresence("message", "imageUrl");
```

**Comment by nebtrx** [comment]
Done! thanks @acamino
