### ISSUE TITLE
No need for fully qualified name

### ISSUE THREAD

**Issue by acamino** [TwilioDevEd/marketing-notifications-servlets#3]
Looks like the fully qualified name is not necessary [here](https://github.com/TwilioDevEd/marketing-notifications-servlets/blob/master/src/main/java/org/twilio/smsmarketing/NotificationsServlet.java#L20), please bear in mind that you'll need to use a full name when there are naming collisions in the class you're working on.

Would you mind double checking please? If this is the case, please remove the unnecessary qualification.

**Comment by nebtrx** [comment]
Fixed!!
