### ISSUE TITLE
Remove static keyword

### ISSUE THREAD

**Issue by acamino** [TwilioDevEd/marketing-notifications-servlets#4]
Actually you don't need to use the `static` keyword [here](https://github.com/TwilioDevEd/marketing-notifications-servlets/blob/master/src/main/java/org/twilio/smsmarketing/TwilioServlet.java#L15-L16), since you're not referencing this attribute outside this class.

Also [here](https://github.com/TwilioDevEd/marketing-notifications-servlets/blob/master/src/main/java/org/twilio/smsmarketing/TwilioServlet.java#L63), there is no need for referencing the class itself `TwilioServlet.SUBSCRIBE_COMMAND`, since this code is in `TwilioServlet` itself.

**Comment by nebtrx** [comment]
Done and Done!
